apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: scram-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      default.replication.factor: 1
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        tls: true
        type: route
        authentication:
          type: scram-sha-512
    replicas: 2
    storage:
      type: jbod
    version: 3.7.0
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: scram-user
  labels:
    strimzi.io/cluster: scram-cluster
spec:
  authentication:
    type: scram-sha-512